### ISSUE TITLE
CocoaPods install issue

### ISSUE THREAD

**Issue by 2113industries** [frederik-jacques/TNImageSliderViewController#12]
I just installed via Cocoapods into my project.  I used the exact code from the example project but I got a ton of errors in the TNImageSliderViewController.swift file.

The only way that I was able to get around this was to copy all of the code from the TNImageSliderViewController.swift from the example project and paste it into the same file in my project.

I'm still getting a handful of "unknown class" errors for TNImageSliderView and TNImageSliderViewController.

Also getting crash from a found nil optional on this line...
`imageSliderVC.images = [image1, image2, image3]`

**Comment by frederik-jacques** [comment]
I just updated the podspec with a new version which removes the errors for Xcode 7.3 & Swift 2.2
