### ISSUE TITLE
how to use on SWIFT 2

### ISSUE THREAD

**Issue by hamid2005** [frederik-jacques/TNImageSliderViewController#4]
I couldn't use this on Swift 2 . Is there any update for that ?

Thanks

**Comment by shanmarkus** [comment]
- 1

**Comment by shanmarkus** [comment]
@hamid2005 try 

pod "TNImageSliderViewController", :git => 'https://github.com/lyh2668/TNImageSliderViewController'

it not merge yet

**Comment by ghost** [comment]
@shanmarkus Thank you! pod still not merged, you saved the day.

**Comment by frederik-jacques** [comment]
i just updated the pods with support for Xcode 7.3 and Swift 2.2
