### ISSUE TITLE
Get index of displayed image

### ISSUE THREAD

**Issue by Nexmind** [frederik-jacques/TNImageSliderViewController#9]
Hi,
I would like to know if there are a way to get the index of displayed image. I would like add a "delete" button for delete the displayed image of the slider. 

Thank you for this good library :-)

Regards

**Comment by frederik-jacques** [comment]
This is now possible in version 1.0.3. Just implement the delegate method and you'll get the index (0-based) of the picture being shown when the user scrolled.
